name: Windows Release

on:
  push:
    branches:
      - 'trunk'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'trunk'

env:
  PROG: cubiomes-viewer

jobs:
  build:
    name: build-windows-static
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 with Static Qt6
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: false
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-qt6-static
            make

      - name: Build
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/qt6-static/bin:$PATH"
          qmake6 CONFIG+=release CONFIG+=static "QMAKE_LFLAGS += -static -static-libgcc -static-libstdc++"
          make -j$(nproc)

      - name: Test Executable
        shell: msys2 {0}
        run: |
          ./release/${{ env.PROG }}.exe --version

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROG }}-win-static
          path: release/${{ env.PROG }}.exe
