name: Windows Release

on:
  push:
    branches:
      - 'trunk'
    tags:
      - 'v*'

defaults:
  run:
    shell: msys2 {0}

env:
  PROG:         cubiomes-viewer
  SOURCE_DIR:   ${{github.workspace}}


jobs:
  build:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-cross-mingwarm64-gcc
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-tools

      - name: Build
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              canon_path=$(cygpath -u "$SOURCE_DIR")
              echo "canonical_source_dir=${canon_path}" >> $GITHUB_ENV
              qmake-qt5 CONFIG+=release $canon_path
              make
              
      - name: Deploy
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              mkdir ${{env.PROG}}
              cp ${{env.canonical_source_dir}}/release/${{env.PROG}}.exe ${{env.PROG}}
              windeployqt-qt5 --dir ${{env.PROG}} ${{env.canonical_source_dir}}/release/${{env.PROG}}.exe --compiler-runtime --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle
              ${{env.canonical_source_dir}}/${{env.PROG}}/${{env.PROG}}.exe --version

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROG}}-win
          path: ${{env.SOURCE_DIR}}\${{env.PROG}}


